# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='rarity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anon', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='rat',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
