# Generated by Django 5.2.4 on 2025-07-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rat',
            old_name='rat_id',
            new_name='qr_number',
        ),
    ]
