# Generated by Django 5.2.4 on 2025-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anon', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='rat',
            name='rat_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rat',
            name='scale',
            field=models.CharField(max_length=100),
        ),
    ]
