# Generated by Django 5.2.4 on 2025-07-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat_type', models.CharField()),
                ('scale', models.CharField()),
                ('caught', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rats',
        ),
    ]
