# Generated by Django 5.2.4 on 2025-07-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='rat_id',
            field=models.IntegerField(default=0),
        ),
    ]
