# Generated by Django 5.2.4 on 2025-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rat_delete_rats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='rat_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rat',
            name='scale',
            field=models.CharField(max_length=100),
        ),
    ]
