# Generated by Django 5.2.4 on 2025-07-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rat_rarity_alter_customuser_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rat',
            name='rarity',
        ),
    ]
