# Generated by Django 5.2.4 on 2025-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_rat_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='rarity',
            field=models.IntegerField(null=True),
        ),
    ]
