# Generated by Django 5.2.4 on 2025-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat_type', models.CharField()),
                ('scale', models.CharField()),
                ('caught', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('rat_id', models.IntegerField()),
            ],
        ),
    ]
